@startuml
interface ILog {
    Log(msg:string, color:LogColor) : void
    Wain(msg:string, color:LogColor) : void
    Error(msg:string, color:LogColor) : void
    Debug(msg:string, color:LogColor) : void
    ColorLog(msg:string, color:LogColor) : void
}
enum LogColor {
    None,
    Red,
    Green,
    Blue,
    Cyan,
    Magenta,
    Yellow,
    Black,
}
ILog --> LogColor
@enduml
